USE pizza;

CREATE TABLE STORES(
STORE_ID INT(3) AUTO_INCREMENT,
STORE_NAME VARCHAR(50),
PRIMARY KEY (STORE_ID)
);

CREATE TABLE DRIVERS(
DRIVER_NAME VARCHAR(50),
DRIVER_STORE_ID INT(3),
PRIMARY KEY (DRIVER_NAME, DRIVER_STORE_ID)
);

CREATE TABLE PIZZAS(
STORE_ID INT(3),
PIZZA_ID BIGINT AUTO_INCREMENT,
PIZZA_NAME VARCHAR(50),
PIZZA_TOPPINGS VARCHAR(150),
PRIMARY KEY (PIZZA_ID)
);

CREATE TABLE CUSTOMERS(
CUSTOMER_ID BIGINT AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(50),
CUSTOMER_ADDRESS VARCHAR(150),
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS(
ORDER_ID BIGINT,
CUSTOMER_ID BIGINT,
ORDER_DATE VARCHAR(50),
STORE_ID CHAR(3),
PIZZA_NAMES VARCHAR(150),
PRIMARY KEY (ORDER_ID)
);