USE pizza;

CREATE TABLE STORES(
STORE_ID INT(3) AUTO_INCREMENT,
STORE_NAME VARCHAR(50),
PRIMARY KEY (STORE_ID)
);

CREATE TABLE DRIVERS(
DRIVER_NAME VARCHAR(50),
DRIVER_STORE_ID INT(3),
PRIMARY KEY (DRIVER_NAME)
);

CREATE TABLE PIZZAS(
STORE_ID INT(3),
PIZZA_ID BIGINT,
PIZZA_NAME VARCHAR(50),
PIZZA_TOPPINGS VARCHAR(150),
PRIMARY KEY (STORE_ID, PIZZA_NAME)
);

CREATE TABLE CUSTOMERS(
CUSTOMER_ID BIGINT,
CUSTOMER_NAME VARCHAR(50),
PRIMARY KEY (CUSTOMER_ID, CUSTOMER_NAME)
);

CREATE TABLE ORDERS(
ORDER_ID BIGINT,
CUSTOMER_ID BIGINT,
ORDER_DATE DATE,
STORE_ID CHAR(3),
PIZZA_NAME VARCHAR(50),
PRIMARY KEY (ORDER_ID)
);